# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               'Arch.Digital'
tagline:             'Software Development Experts'
description:         'Software Development Process Experts, Ruby on Rails, Application Maturity'
url:                 https://arch.digital
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nick Urban
  url:               https://twitter.com/nickurban
  email:             nick@arch.digital

# Custom vars
version:             1.0.0
